// Code generated by tangentgen; DO NOT EDIT.

package tests

import (
	pluginout "github.com/telophasehq/tangent_sdk"
)

// AppendToArena appends MyStructPtr into the arena as an object and returns the root node index.
func (x MyStructPtr) AppendToArena(ab *pluginout.ArenaBuilder) uint32 {
	ab.ObjectStart()

	MyInt_int_idx := ab.Int(int64(x.MyInt))
	ab.ObjectAdd(ab.Field("MyInt", MyInt_int_idx))
	MyFloat_float_idx := ab.Float(float64(x.MyFloat))
	ab.ObjectAdd(ab.Field("MyFloat", MyFloat_float_idx))
	MyString_str_idx := ab.String(x.MyString)
	ab.ObjectAdd(ab.Field("MyString", MyString_str_idx))
	if x.MyNested != nil {
		idx := x.MyNested.AppendToArena(ab)
		ab.ObjectAdd(ab.Field("MyNested", idx))
	}
	ab.ArrayStart()
	for i := range x.MyList {
		ab.ArrayAdd(ab.String(x.MyList[i]))
	}
	idx := ab.ArrayEnd()
	ab.ObjectAdd(ab.Field("MyList", idx))

	return ab.ObjectEnd()
}

// AppendToArena appends MyNested into the arena as an object and returns the root node index.
func (x MyNested) AppendToArena(ab *pluginout.ArenaBuilder) uint32 {
	ab.ObjectStart()

	MyNestedInt_int_idx := ab.Int(int64(x.MyNestedInt))
	ab.ObjectAdd(ab.Field("MyNestedInt", MyNestedInt_int_idx))

	return ab.ObjectEnd()
}
