// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package tests

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3b37e15cDecodeGithubComTelophasehqTangentSdkTests(in *jlexer.Lexer, out *MyStructPtr) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "my_int":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MyInt = int(in.Int())
			}
		case "my_float":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MyFloat = float64(in.Float64())
			}
		case "my_string":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MyString = string(in.String())
			}
		case "my_nested":
			if in.IsNull() {
				in.Skip()
				out.MyNested = nil
			} else {
				if out.MyNested == nil {
					out.MyNested = new(MyNested)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.MyNested).UnmarshalEasyJSON(in)
				}
			}
		case "my_list":
			if in.IsNull() {
				in.Skip()
				out.MyList = nil
			} else {
				in.Delim('[')
				if out.MyList == nil {
					if !in.IsDelim(']') {
						out.MyList = make([]string, 0, 4)
					} else {
						out.MyList = []string{}
					}
				} else {
					out.MyList = (out.MyList)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.MyList = append(out.MyList, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b37e15cEncodeGithubComTelophasehqTangentSdkTests(out *jwriter.Writer, in MyStructPtr) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"my_int\":"
		out.RawString(prefix[1:])
		out.Int(int(in.MyInt))
	}
	{
		const prefix string = ",\"my_float\":"
		out.RawString(prefix)
		out.Float64(float64(in.MyFloat))
	}
	{
		const prefix string = ",\"my_string\":"
		out.RawString(prefix)
		out.String(string(in.MyString))
	}
	{
		const prefix string = ",\"my_nested\":"
		out.RawString(prefix)
		if in.MyNested == nil {
			out.RawString("null")
		} else {
			(*in.MyNested).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"my_list\":"
		out.RawString(prefix)
		if in.MyList == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.MyList {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MyStructPtr) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b37e15cEncodeGithubComTelophasehqTangentSdkTests(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MyStructPtr) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b37e15cEncodeGithubComTelophasehqTangentSdkTests(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MyStructPtr) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b37e15cDecodeGithubComTelophasehqTangentSdkTests(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MyStructPtr) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b37e15cDecodeGithubComTelophasehqTangentSdkTests(l, v)
}
func easyjson3b37e15cDecodeGithubComTelophasehqTangentSdkTests1(in *jlexer.Lexer, out *MyStructAnonPtr) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "my_int":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MyInt = int(in.Int())
			}
		case "my_float":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MyFloat = float64(in.Float64())
			}
		case "my_string":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MyString = string(in.String())
			}
		case "my_nested":
			if in.IsNull() {
				in.Skip()
				out.MyNested = nil
			} else {
				if out.MyNested == nil {
					out.MyNested = new(struct {
						MyNestedInt int `json:"nested_int"`
					})
				}
				easyjson3b37e15cDecode(in, out.MyNested)
			}
		case "my_list":
			if in.IsNull() {
				in.Skip()
				out.MyList = nil
			} else {
				in.Delim('[')
				if out.MyList == nil {
					if !in.IsDelim(']') {
						out.MyList = make([]string, 0, 4)
					} else {
						out.MyList = []string{}
					}
				} else {
					out.MyList = (out.MyList)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					if in.IsNull() {
						in.Skip()
					} else {
						v4 = string(in.String())
					}
					out.MyList = append(out.MyList, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b37e15cEncodeGithubComTelophasehqTangentSdkTests1(out *jwriter.Writer, in MyStructAnonPtr) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"my_int\":"
		out.RawString(prefix[1:])
		out.Int(int(in.MyInt))
	}
	{
		const prefix string = ",\"my_float\":"
		out.RawString(prefix)
		out.Float64(float64(in.MyFloat))
	}
	{
		const prefix string = ",\"my_string\":"
		out.RawString(prefix)
		out.String(string(in.MyString))
	}
	{
		const prefix string = ",\"my_nested\":"
		out.RawString(prefix)
		if in.MyNested == nil {
			out.RawString("null")
		} else {
			easyjson3b37e15cEncode(out, *in.MyNested)
		}
	}
	{
		const prefix string = ",\"my_list\":"
		out.RawString(prefix)
		if in.MyList == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.MyList {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MyStructAnonPtr) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b37e15cEncodeGithubComTelophasehqTangentSdkTests1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MyStructAnonPtr) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b37e15cEncodeGithubComTelophasehqTangentSdkTests1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MyStructAnonPtr) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b37e15cDecodeGithubComTelophasehqTangentSdkTests1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MyStructAnonPtr) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b37e15cDecodeGithubComTelophasehqTangentSdkTests1(l, v)
}
func easyjson3b37e15cDecode(in *jlexer.Lexer, out *struct {
	MyNestedInt int `json:"nested_int"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "nested_int":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MyNestedInt = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b37e15cEncode(out *jwriter.Writer, in struct {
	MyNestedInt int `json:"nested_int"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"nested_int\":"
		out.RawString(prefix[1:])
		out.Int(int(in.MyNestedInt))
	}
	out.RawByte('}')
}
func easyjson3b37e15cDecodeGithubComTelophasehqTangentSdkTests2(in *jlexer.Lexer, out *MyStructAnon) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "my_int":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MyInt = int(in.Int())
			}
		case "my_float":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MyFloat = float64(in.Float64())
			}
		case "my_string":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MyString = string(in.String())
			}
		case "my_nested":
			easyjson3b37e15cDecode(in, &out.MyNested)
		case "my_list":
			if in.IsNull() {
				in.Skip()
				out.MyList = nil
			} else {
				in.Delim('[')
				if out.MyList == nil {
					if !in.IsDelim(']') {
						out.MyList = make([]string, 0, 4)
					} else {
						out.MyList = []string{}
					}
				} else {
					out.MyList = (out.MyList)[:0]
				}
				for !in.IsDelim(']') {
					var v7 string
					if in.IsNull() {
						in.Skip()
					} else {
						v7 = string(in.String())
					}
					out.MyList = append(out.MyList, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b37e15cEncodeGithubComTelophasehqTangentSdkTests2(out *jwriter.Writer, in MyStructAnon) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"my_int\":"
		out.RawString(prefix[1:])
		out.Int(int(in.MyInt))
	}
	{
		const prefix string = ",\"my_float\":"
		out.RawString(prefix)
		out.Float64(float64(in.MyFloat))
	}
	{
		const prefix string = ",\"my_string\":"
		out.RawString(prefix)
		out.String(string(in.MyString))
	}
	{
		const prefix string = ",\"my_nested\":"
		out.RawString(prefix)
		easyjson3b37e15cEncode(out, in.MyNested)
	}
	{
		const prefix string = ",\"my_list\":"
		out.RawString(prefix)
		if in.MyList == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.MyList {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.String(string(v9))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MyStructAnon) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b37e15cEncodeGithubComTelophasehqTangentSdkTests2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MyStructAnon) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b37e15cEncodeGithubComTelophasehqTangentSdkTests2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MyStructAnon) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b37e15cDecodeGithubComTelophasehqTangentSdkTests2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MyStructAnon) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b37e15cDecodeGithubComTelophasehqTangentSdkTests2(l, v)
}
func easyjson3b37e15cDecodeGithubComTelophasehqTangentSdkTests3(in *jlexer.Lexer, out *MyStruct) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "my_int":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MyInt = int(in.Int())
			}
		case "my_float":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MyFloat = float64(in.Float64())
			}
		case "my_string":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MyString = string(in.String())
			}
		case "my_nested":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.MyNested).UnmarshalEasyJSON(in)
			}
		case "my_list":
			if in.IsNull() {
				in.Skip()
				out.MyList = nil
			} else {
				in.Delim('[')
				if out.MyList == nil {
					if !in.IsDelim(']') {
						out.MyList = make([]string, 0, 4)
					} else {
						out.MyList = []string{}
					}
				} else {
					out.MyList = (out.MyList)[:0]
				}
				for !in.IsDelim(']') {
					var v10 string
					if in.IsNull() {
						in.Skip()
					} else {
						v10 = string(in.String())
					}
					out.MyList = append(out.MyList, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b37e15cEncodeGithubComTelophasehqTangentSdkTests3(out *jwriter.Writer, in MyStruct) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"my_int\":"
		out.RawString(prefix[1:])
		out.Int(int(in.MyInt))
	}
	{
		const prefix string = ",\"my_float\":"
		out.RawString(prefix)
		out.Float64(float64(in.MyFloat))
	}
	{
		const prefix string = ",\"my_string\":"
		out.RawString(prefix)
		out.String(string(in.MyString))
	}
	{
		const prefix string = ",\"my_nested\":"
		out.RawString(prefix)
		(in.MyNested).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"my_list\":"
		out.RawString(prefix)
		if in.MyList == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.MyList {
				if v11 > 0 {
					out.RawByte(',')
				}
				out.String(string(v12))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MyStruct) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b37e15cEncodeGithubComTelophasehqTangentSdkTests3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MyStruct) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b37e15cEncodeGithubComTelophasehqTangentSdkTests3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MyStruct) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b37e15cDecodeGithubComTelophasehqTangentSdkTests3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MyStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b37e15cDecodeGithubComTelophasehqTangentSdkTests3(l, v)
}
func easyjson3b37e15cDecodeGithubComTelophasehqTangentSdkTests4(in *jlexer.Lexer, out *MyNested) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "nested_int":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MyNestedInt = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3b37e15cEncodeGithubComTelophasehqTangentSdkTests4(out *jwriter.Writer, in MyNested) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"nested_int\":"
		out.RawString(prefix[1:])
		out.Int(int(in.MyNestedInt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MyNested) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3b37e15cEncodeGithubComTelophasehqTangentSdkTests4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MyNested) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3b37e15cEncodeGithubComTelophasehqTangentSdkTests4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MyNested) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3b37e15cDecodeGithubComTelophasehqTangentSdkTests4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MyNested) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3b37e15cDecodeGithubComTelophasehqTangentSdkTests4(l, v)
}
