// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package config represents the imported interface "tangent:logs/config@0.1.0".
package config

import (
	"go.bytecodealliance.org/cm"
)

// Get represents the imported function "get".
//
//	get: func(key: string) -> option<string>
//
//go:nosplit
func Get(key string) (result cm.Option[string]) {
	key0, key1 := cm.LowerString(key)
	wasmimport_Get((*uint8)(key0), (uint32)(key1), &result)
	return
}
