// Code generated by wit-bindgen-go. DO NOT EDIT.

package config

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "tangent:logs@0.1.0".

//go:wasmimport tangent:logs/config@0.1.0 get
//go:noescape
func wasmimport_Get(key0 *uint8, key1 uint32, result *cm.Option[string])
