// Code generated by wit-bindgen-go. DO NOT EDIT.

package mapper

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// TupleStringScalarShape is used for storage in variant or result types.
type TupleStringScalarShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(cm.Tuple[string, Scalar]{})]byte
}
