// Code generated by wit-bindgen-go. DO NOT EDIT.

package mapper

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "tangent:logs@0.1.0".

//go:wasmexport tangent:logs/mapper@0.1.0#metadata
//export tangent:logs/mapper@0.1.0#metadata
func wasmexport_Metadata() (result *Meta) {
	result_ := Exports.Metadata()
	result = &result_
	return
}

//go:wasmexport tangent:logs/mapper@0.1.0#probe
//export tangent:logs/mapper@0.1.0#probe
func wasmexport_Probe() (result *cm.List[Selector]) {
	result_ := Exports.Probe()
	result = &result_
	return
}

//go:wasmexport tangent:logs/mapper@0.1.0#process-logs
//export tangent:logs/mapper@0.1.0#process-logs
func wasmexport_ProcessLogs(input0 *Logview, input1 uint32) (result *cm.Result[cm.List[uint8], cm.List[uint8], string]) {
	input := cm.LiftList[cm.List[Logview]]((*Logview)(input0), (uint32)(input1))
	result_ := Exports.ProcessLogs(input)
	result = &result_
	return
}
