// Code generated by wit-bindgen-go. DO NOT EDIT.

package mapper

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "tangent:logs/mapper@0.1.0".
var Exports struct {
	// Metadata represents the caller-defined, exported function "metadata".
	//
	//	metadata: func() -> meta
	Metadata func() (result Meta)

	// Probe represents the caller-defined, exported function "probe".
	//
	//	probe: func() -> list<selector>
	Probe func() (result cm.List[Selector])

	// ProcessLogs represents the caller-defined, exported function "process-logs".
	//
	//	process-logs: func(input: list<borrow<logview>>) -> result<list<u8>, string>
	ProcessLogs func(input cm.List[cm.Rep]) (result cm.Result[cm.List[uint8], cm.List[uint8], string])
}
