// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package mapper represents the exported interface "tangent:logs/mapper@0.1.0".
package mapper

import (
	"github.com/telophasehq/tangent-sdk-go/internal/tangent/logs/log"
	"go.bytecodealliance.org/cm"
)

// Logview represents the exported type alias "tangent:logs/mapper@0.1.0#logview".
//
// See [log.Logview] for more information.
type Logview = log.Logview

// Scalar represents the type alias "tangent:logs/mapper@0.1.0#scalar".
//
// See [log.Scalar] for more information.
type Scalar = log.Scalar

// Meta represents the record "tangent:logs/mapper@0.1.0#meta".
//
//	record meta {
//		name: string,
//		version: string,
//	}
type Meta struct {
	_       cm.HostLayout `json:"-"`
	Name    string        `json:"name"`
	Version string        `json:"version"`
}

// Pred represents the variant "tangent:logs/mapper@0.1.0#pred".
//
//	variant pred {
//		has(string),
//		eq(tuple<string, scalar>),
//		prefix(tuple<string, string>),
//		in(tuple<string, list<scalar>>),
//		gt(tuple<string, f64>),
//		regex(tuple<string, string>),
//	}
type Pred cm.Variant[uint8, TupleStringScalarShape, cm.Tuple[string, Scalar]]

// PredHas returns a [Pred] of case "has".
func PredHas(data string) Pred {
	return cm.New[Pred](0, data)
}

// Has returns a non-nil *[string] if [Pred] represents the variant case "has".
func (self *Pred) Has() *string {
	return cm.Case[string](self, 0)
}

// PredEq returns a [Pred] of case "eq".
func PredEq(data cm.Tuple[string, Scalar]) Pred {
	return cm.New[Pred](1, data)
}

// Eq returns a non-nil *[cm.Tuple[string, Scalar]] if [Pred] represents the variant case "eq".
func (self *Pred) Eq() *cm.Tuple[string, Scalar] {
	return cm.Case[cm.Tuple[string, Scalar]](self, 1)
}

// PredPrefix returns a [Pred] of case "prefix".
func PredPrefix(data [2]string) Pred {
	return cm.New[Pred](2, data)
}

// Prefix returns a non-nil *[[2]string] if [Pred] represents the variant case "prefix".
func (self *Pred) Prefix() *[2]string {
	return cm.Case[[2]string](self, 2)
}

// PredIn returns a [Pred] of case "in".
func PredIn(data cm.Tuple[string, cm.List[Scalar]]) Pred {
	return cm.New[Pred](3, data)
}

// In returns a non-nil *[cm.Tuple[string, cm.List[Scalar]]] if [Pred] represents the variant case "in".
func (self *Pred) In() *cm.Tuple[string, cm.List[Scalar]] {
	return cm.Case[cm.Tuple[string, cm.List[Scalar]]](self, 3)
}

// PredGt returns a [Pred] of case "gt".
func PredGt(data cm.Tuple[string, float64]) Pred {
	return cm.New[Pred](4, data)
}

// Gt returns a non-nil *[cm.Tuple[string, float64]] if [Pred] represents the variant case "gt".
func (self *Pred) Gt() *cm.Tuple[string, float64] {
	return cm.Case[cm.Tuple[string, float64]](self, 4)
}

// PredRegex returns a [Pred] of case "regex".
func PredRegex(data [2]string) Pred {
	return cm.New[Pred](5, data)
}

// Regex returns a non-nil *[[2]string] if [Pred] represents the variant case "regex".
func (self *Pred) Regex() *[2]string {
	return cm.Case[[2]string](self, 5)
}

var _PredStrings = [6]string{
	"has",
	"eq",
	"prefix",
	"in",
	"gt",
	"regex",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v Pred) String() string {
	return _PredStrings[v.Tag()]
}

// Selector represents the record "tangent:logs/mapper@0.1.0#selector".
//
//	record selector {
//		any: list<pred>,
//		all: list<pred>,
//		none: list<pred>,
//	}
type Selector struct {
	_   cm.HostLayout `json:"-"`
	Any cm.List[Pred] `json:"any"`

	// OR of predicates
	All cm.List[Pred] `json:"all"`

	// AND of predicates
	None cm.List[Pred] `json:"none"`
}

// Idx represents the u32 "tangent:logs/mapper@0.1.0#idx".
//
//	type idx = u32
type Idx uint32

// Field represents the record "tangent:logs/mapper@0.1.0#field".
//
//	record field {
//		keyid: u32,
//		val: idx,
//	}
type Field struct {
	_     cm.HostLayout `json:"-"`
	Keyid uint32        `json:"keyid"`
	Val   Idx           `json:"val"`
}

// Node represents the variant "tangent:logs/mapper@0.1.0#node".
//
//	variant node {
//		null,
//		%string(string),
//		integer(s64),
//		float(f64),
//		boolean(bool),
//		bytes(list<u8>),
//		array(list<idx>),
//		object(list<field>),
//	}
type Node cm.Variant[uint8, string, int64]

// NodeNull returns a [Node] of case "null".
func NodeNull() Node {
	var data struct{}
	return cm.New[Node](0, data)
}

// Null returns true if [Node] represents the variant case "null".
func (self *Node) Null() bool {
	return self.Tag() == 0
}

// NodeString_ returns a [Node] of case "string".
func NodeString_(data string) Node {
	return cm.New[Node](1, data)
}

// String_ returns a non-nil *[string] if [Node] represents the variant case "string".
func (self *Node) String_() *string {
	return cm.Case[string](self, 1)
}

// NodeInteger returns a [Node] of case "integer".
func NodeInteger(data int64) Node {
	return cm.New[Node](2, data)
}

// Integer returns a non-nil *[int64] if [Node] represents the variant case "integer".
func (self *Node) Integer() *int64 {
	return cm.Case[int64](self, 2)
}

// NodeFloat returns a [Node] of case "float".
func NodeFloat(data float64) Node {
	return cm.New[Node](3, data)
}

// Float returns a non-nil *[float64] if [Node] represents the variant case "float".
func (self *Node) Float() *float64 {
	return cm.Case[float64](self, 3)
}

// NodeBoolean returns a [Node] of case "boolean".
func NodeBoolean(data bool) Node {
	return cm.New[Node](4, data)
}

// Boolean returns a non-nil *[bool] if [Node] represents the variant case "boolean".
func (self *Node) Boolean() *bool {
	return cm.Case[bool](self, 4)
}

// NodeBytes returns a [Node] of case "bytes".
func NodeBytes(data cm.List[uint8]) Node {
	return cm.New[Node](5, data)
}

// Bytes returns a non-nil *[cm.List[uint8]] if [Node] represents the variant case "bytes".
func (self *Node) Bytes() *cm.List[uint8] {
	return cm.Case[cm.List[uint8]](self, 5)
}

// NodeArray returns a [Node] of case "array".
func NodeArray(data cm.List[Idx]) Node {
	return cm.New[Node](6, data)
}

// Array returns a non-nil *[cm.List[Idx]] if [Node] represents the variant case "array".
func (self *Node) Array() *cm.List[Idx] {
	return cm.Case[cm.List[Idx]](self, 6)
}

// NodeObject returns a [Node] of case "object".
func NodeObject(data cm.List[Field]) Node {
	return cm.New[Node](7, data)
}

// Object returns a non-nil *[cm.List[Field]] if [Node] represents the variant case "object".
func (self *Node) Object() *cm.List[Field] {
	return cm.Case[cm.List[Field]](self, 7)
}

var _NodeStrings = [8]string{
	"null",
	"string",
	"integer",
	"float",
	"boolean",
	"bytes",
	"array",
	"object",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v Node) String() string {
	return _NodeStrings[v.Tag()]
}

// Batchout represents the record "tangent:logs/mapper@0.1.0#batchout".
//
//	record batchout {
//		strings: list<string>,
//		arena: list<node>,
//		roots: list<idx>,
//	}
type Batchout struct {
	_       cm.HostLayout   `json:"-"`
	Strings cm.List[string] `json:"strings"`
	Arena   cm.List[Node]   `json:"arena"`
	Roots   cm.List[Idx]    `json:"roots"`
}
