// Code generated by wit-bindgen-go. DO NOT EDIT.

package remote

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "tangent:logs@0.1.0".

//go:wasmimport tangent:logs/remote@0.1.0 call-batch
//go:noescape
func wasmimport_CallBatch(reqs0 *Request, reqs1 uint32, result *cm.Result[cm.List[Response], cm.List[Response], string])
