// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package remote represents the imported interface "tangent:logs/remote@0.1.0".
package remote

import (
	"go.bytecodealliance.org/cm"
)

// Method represents the enum "tangent:logs/remote@0.1.0#method".
//
//	enum method {
//		get,
//		post,
//		put,
//		delete,
//		patch
//	}
type Method uint8

const (
	MethodGet Method = iota
	MethodPost
	MethodPut
	MethodDelete
	MethodPatch
)

var _MethodStrings = [5]string{
	"get",
	"post",
	"put",
	"delete",
	"patch",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e Method) String() string {
	return _MethodStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e Method) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *Method) UnmarshalText(text []byte) error {
	return _MethodUnmarshalCase(e, text)
}

var _MethodUnmarshalCase = cm.CaseUnmarshaler[Method](_MethodStrings[:])

// Request represents the record "tangent:logs/remote@0.1.0#request".
//
//	record request {
//		id: string,
//		method: method,
//		url: string,
//		headers: list<tuple<string, string>>,
//		body: list<u8>,
//		timeout-ms: option<u32>,
//		cache-ttl-ms: option<u32>,
//	}
type Request struct {
	_          cm.HostLayout      `json:"-"`
	ID         string             `json:"id"`
	Method     Method             `json:"method"`
	URL        string             `json:"url"`
	Headers    cm.List[[2]string] `json:"headers"`
	Body       cm.List[uint8]     `json:"body"`
	TimeoutMs  cm.Option[uint32]  `json:"timeout-ms"`
	CacheTTLMs cm.Option[uint32]  `json:"cache-ttl-ms"`
}

// Response represents the record "tangent:logs/remote@0.1.0#response".
//
//	record response {
//		id: string,
//		status: u16,
//		headers: list<tuple<string, string>>,
//		body: list<u8>,
//		error: option<string>,
//	}
type Response struct {
	_       cm.HostLayout      `json:"-"`
	ID      string             `json:"id"`
	Status  uint16             `json:"status"`
	Headers cm.List[[2]string] `json:"headers"`
	Body    cm.List[uint8]     `json:"body"`
	Error   cm.Option[string]  `json:"error"`
}

// CallBatch represents the imported function "call-batch".
//
//	call-batch: func(reqs: list<request>) -> result<list<response>, string>
//
//go:nosplit
func CallBatch(reqs cm.List[Request]) (result cm.Result[cm.List[Response], cm.List[Response], string]) {
	reqs0, reqs1 := cm.LowerList(reqs)
	wasmimport_CallBatch((*Request)(reqs0), (uint32)(reqs1), &result)
	return
}
