// Code generated by wit-bindgen-go. DO NOT EDIT.

package cache

import (
	"github.com/telophasehq/tangent-sdk-go/internal/tangent/logs/log"
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// OptionScalarShape is used for storage in variant or result types.
type OptionScalarShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(cm.Option[Scalar]{})]byte
}

func lower_Scalar(v log.Scalar) (f0 uint32, f1 uint64, f2 uint32) {
	f0 = (uint32)(v.Tag())
	switch f0 {
	case 0: // str
		v1, v2 := cm.LowerString(*cm.Case[string](&v, 0))
		f1 = (uint64)(cm.PointerToU64(v1))
		f2 = (uint32)(v2)
	case 1: // int
		v1 := (uint64)(*cm.Case[int64](&v, 1))
		f1 = (uint64)(v1)
	case 2: // float
		v1 := (float64)(*cm.Case[float64](&v, 2))
		f1 = (uint64)(cm.F64ToU64(v1))
	case 3: // boolean
		v1 := (uint32)(cm.BoolToU32(*cm.Case[bool](&v, 3)))
		f1 = (uint64)(v1)
	case 4: // bytes
		v1, v2 := cm.LowerList(*cm.Case[cm.List[uint8]](&v, 4))
		f1 = (uint64)(cm.PointerToU64(v1))
		f2 = (uint32)(v2)
	}
	return
}

func lower_OptionU64(v cm.Option[uint64]) (f0 uint32, f1 uint64) {
	some := v.Some()
	if some != nil {
		f0 = 1
		v1 := (uint64)(*some)
		f1 = (uint64)(v1)
	}
	return
}
