// Code generated by wit-bindgen-go. DO NOT EDIT.

package cache

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "tangent:logs@0.1.0".

//go:wasmimport tangent:logs/cache@0.1.0 get
//go:noescape
func wasmimport_Get(key0 *uint8, key1 uint32, result *cm.Result[OptionScalarShape, cm.Option[Scalar], string])

//go:wasmimport tangent:logs/cache@0.1.0 set
//go:noescape
func wasmimport_Set(key0 *uint8, key1 uint32, value0 uint32, value1 uint64, value2 uint32, ttlMs0 uint32, ttlMs1 uint64, result *cm.Result[string, struct{}, string])

//go:wasmimport tangent:logs/cache@0.1.0 del
//go:noescape
func wasmimport_Del(key0 *uint8, key1 uint32, result *cm.Result[string, bool, string])
