// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package cache represents the imported interface "tangent:logs/cache@0.1.0".
package cache

import (
	"github.com/telophasehq/tangent-sdk-go/internal/tangent/logs/log"
	"go.bytecodealliance.org/cm"
)

// Scalar represents the type alias "tangent:logs/cache@0.1.0#scalar".
//
// See [log.Scalar] for more information.
type Scalar = log.Scalar

// Get represents the imported function "get".
//
//	get: func(key: string) -> result<option<scalar>, string>
//
//go:nosplit
func Get(key string) (result cm.Result[OptionScalarShape, cm.Option[Scalar], string]) {
	key0, key1 := cm.LowerString(key)
	wasmimport_Get((*uint8)(key0), (uint32)(key1), &result)
	return
}

// Set represents the imported function "set".
//
//	set: func(key: string, value: scalar, ttl-ms: option<u64>) -> result<_, string>
//
//go:nosplit
func Set(key string, value Scalar, ttlMs cm.Option[uint64]) (result cm.Result[string, struct{}, string]) {
	key0, key1 := cm.LowerString(key)
	value0, value1, value2 := lower_Scalar(value)
	ttlMs0, ttlMs1 := lower_OptionU64(ttlMs)
	wasmimport_Set((*uint8)(key0), (uint32)(key1), (uint32)(value0), (uint64)(value1), (uint32)(value2), (uint32)(ttlMs0), (uint64)(ttlMs1), &result)
	return
}

// Del represents the imported function "del".
//
//	del: func(key: string) -> result<bool, string>
//
//go:nosplit
func Del(key string) (result cm.Result[string, bool, string]) {
	key0, key1 := cm.LowerString(key)
	wasmimport_Del((*uint8)(key0), (uint32)(key1), &result)
	return
}
