// Code generated by wit-bindgen-go. DO NOT EDIT.

package lock

// This file contains wasmimport and wasmexport declarations for "tangent:logs@0.1.0".

//go:wasmimport tangent:logs/lock@0.1.0 acquire
//go:noescape
func wasmimport_Acquire(key0 *uint8, key1 uint32) (result0 uint32)

//go:wasmimport tangent:logs/lock@0.1.0 release
//go:noescape
func wasmimport_Release(key0 *uint8, key1 uint32)
