// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package lock represents the imported interface "tangent:logs/lock@0.1.0".
package lock

import (
	"go.bytecodealliance.org/cm"
)

// Acquire represents the imported function "acquire".
//
//	acquire: func(key: string) -> bool
//
//go:nosplit
func Acquire(key string) (result bool) {
	key0, key1 := cm.LowerString(key)
	result0 := wasmimport_Acquire((*uint8)(key0), (uint32)(key1))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// Release represents the imported function "release".
//
//	release: func(key: string)
//
//go:nosplit
func Release(key string) {
	key0, key1 := cm.LowerString(key)
	wasmimport_Release((*uint8)(key0), (uint32)(key1))
	return
}
