// Code generated by wit-bindgen-go. DO NOT EDIT.

package log

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "tangent:logs@0.1.0".

//go:wasmimport tangent:logs/log@0.1.0 [resource-drop]logview
//go:noescape
func wasmimport_LogviewResourceDrop(self0 uint32)

//go:wasmimport tangent:logs/log@0.1.0 [method]logview.get
//go:noescape
func wasmimport_LogviewGet(self0 uint32, path0 *uint8, path1 uint32, result *cm.Option[Scalar])

//go:wasmimport tangent:logs/log@0.1.0 [method]logview.get-list
//go:noescape
func wasmimport_LogviewGetList(self0 uint32, path0 *uint8, path1 uint32, result *cm.Option[cm.List[Scalar]])

//go:wasmimport tangent:logs/log@0.1.0 [method]logview.get-map
//go:noescape
func wasmimport_LogviewGetMap(self0 uint32, path0 *uint8, path1 uint32, result *cm.Option[cm.List[cm.Tuple[string, Scalar]]])

//go:wasmimport tangent:logs/log@0.1.0 [method]logview.has
//go:noescape
func wasmimport_LogviewHas(self0 uint32, path0 *uint8, path1 uint32) (result0 uint32)

//go:wasmimport tangent:logs/log@0.1.0 [method]logview.keys
//go:noescape
func wasmimport_LogviewKeys(self0 uint32, path0 *uint8, path1 uint32, result *cm.List[string])

//go:wasmimport tangent:logs/log@0.1.0 [method]logview.len
//go:noescape
func wasmimport_LogviewLen(self0 uint32, path0 *uint8, path1 uint32, result *cm.Option[uint32])
